// @ts-ignore generated by opennextjs-cloudflare build
import { default as openNextHandler } from "../.open-next/worker.js";

import { BotGatewayDO } from "./bot-gateway-do";
import { handleEventQueueBatch } from "./event-persist";
import { parseGatewayRoute } from "./routes";
import type { Env, EventQueueMessage } from "./env";

export { BotGatewayDO };

const APP_ID_HEADER = "X-Bot-App-Id";

async function resolveAuthAppId(request: Request): Promise<string | null> {
  try {
    const body = (await request.clone().json()) as { appId?: string };
    return body.appId ?? null;
  } catch {
    return null;
  }
}

function forwardToDo(request: Request, env: Env, appId: string) {
  const headers = new Headers(request.headers);
  headers.set(APP_ID_HEADER, appId);
  const url = new URL(request.url);
  return env.BOT_GATEWAY.get(env.BOT_GATEWAY.idFromName(appId)).fetch(
    new Request(url, {
      method: request.method,
      headers,
      body: request.body,
      redirect: request.redirect,
    }) as never,
  );
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);
    const route = parseGatewayRoute(url);

    if (route) {
      let appId = route.appId;
      if (route.kind === "auth") {
        appId = await resolveAuthAppId(request);
        if (!appId) {
          return Response.json(
            { msg: "appId required in request body" },
            { status: 400 },
          );
        }
      }
      if (appId) {
        return forwardToDo(request, env, appId);
      }
    }

    return openNextHandler.fetch(request, env, ctx);
  },

  async queue(batch: MessageBatch, env: Env): Promise<void> {
    await handleEventQueueBatch(
      env,
      batch.messages.map((m) => m.body as EventQueueMessage),
    );
  },
};
